### ISSUE TITLE
Enable Scott Glacier Real-time Data

### ISSUE THREAD

**Issue by adamlewinter** [gadomski/glac.io#131]
I'm working on the Overview, Images, and Climate Station Diagram content for the remaining USGS climate stations. @gadomski, will you work with @dcfinnegan to enable the real-time data feed?

**Comment by gadomski** [comment]
@adamlewinter same shtick as #133, can you sanity-check me? Thanks.

**Comment by adamlewinter** [comment]
Will check this evening, enroute to a basin. When can we expect you here, shooting ze howitzer this afternoon...

Thanks for getting the sites up and running. Let's include them in the drop down menus. I'll put in placeholders for any pages that are incomplete.

Cheers,
A

---------------------
Adam LeWinter
Adam.l.lewinter@usace.army.mil
603.921.0849
From: Pete Gadomski
Sent: Wednesday, March 4, 2015 07:56
To: gadomski/glac.io
Reply To: gadomski/glac.io
Cc: Lewinter, Adam ERDC-CRREL-NH CONTRACTOR
Subject: [EXTERNAL] Re: [glac.io] Enable Scott Glacier Real-time Data (#131)



@adamlewinter<https://github.com/adamlewinter> same shtick as #133<https://github.com/gadomski/glac.io/issues/133>, can you sanity-check me? Thanks.

**Comment by gadomski** [comment]
I've updated the dev site w/ the dropdowns, let me know if everything else looks ok.





Who got a howitzer?!?!?

**Comment by adamlewinter** [comment]
@gadomski Scott Glacier data looks good to go. 

Sorry, no Howitzer, just the pressure-pea-shooter they have always had at A Basin. Wishful thinking on my part...
