### ISSUE TITLE
Enable Wolverine Glacier real-time data

### ISSUE THREAD

**Issue by adamlewinter** [gadomski/glac.io#132]
I'm working on the Overview, Images, and Climate Station Diagram content for the remaining USGS climate stations. @gadomski, will you work with @dcfinnegan to enable the real-time data feed?

**Comment by gadomski** [comment]
@dcfinnegan do you have the ts codes for this location, by chance?

**Comment by dcfinnegan** [comment]
10182021	T	T	NAE	WOL.Temp-AIR2.Inst.15Minutes.0.DCP-rev	C	Temperature	WOL
10181021	T	T	NAE	WOL.Temp-AIR1.Inst.15Minutes.0.DCP-rev	C	Temperature	WOL
10183021	T	T	NAE	WOL.Temp-AIR3.Inst.15Minutes.0.DCP-rev	C	Temperature	WOL
8812021	T	T	NAE	WOL.Speed-WIND2.Inst.15Minutes.0.DCP-raw	kph	Linear Speed	WOL
8803021	T	T	NAE	WOL.Volt.Inst.1Hour.0.DCP-raw	volt	Electromotive Potential	WOL
8793021	T	T	NAE	WOL.Temp-AIR1.Inst.15Minutes.0.DCP-raw	C	Temperature	WOL
8801021	T	T	NAE	WOL.Dir-WIND1.Inst.15Minutes.0.DCP-raw	deg	Angle	WOL
8799021	T	T	NAE	WOL.Speed-Wind.Inst.15Minutes.0.DCP-raw	kph	Linear Speed	WOL
8798021	T	T	NAE	WOL.Precip.Inst.15Minutes.0.DCP-raw	mm	Length	WOL
8797021	T	T	NAE	WOL.Temp-AIR3.Inst.15Minutes.0.DCP-raw	C	Temperature	WOL
8795021	T	T	NAE	WOL.Temp-AIR2.Inst.15Minutes.0.DCP-raw	C	Temperature	WOL
8802021	T	T	NAE	WOL.Dir-WIND2.Inst.15Minutes.0.DCP-raw	deg	Angle	WOL

**Comment by gadomski** [comment]
Deployed to the dev site, @adamlewinter can you verify? Thanks.

**Comment by adamlewinter** [comment]
@gadomski Checking the Wolverine site data:

These look good:
-Voltage
-Wind Speed
-Wind direction
-Precipitation

Air Temp is looking a bit wonky. Sensors 1 and 2 reverse on November 3, 2013. They all then end September 5, 2014.

**Comment by gadomski** [comment]
Yeah what's with these air temp sensors? Want me to default to something else? Precip?

**Comment by adamlewinter** [comment]
Default to precipitation again, will contact Shad.

**Comment by dcfinnegan** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

  
          <optgroup label="Wolverine Glacier">
            <option style="color:red;" value="WOL$Volt$">Wolverine Glacier - Battery Voltage </option> 
            <option value="WOL$Temp$AIR1" selected="selected">Wolverine Glacier - Air Temp1</option>
            <option value="WOL$Temp$AIR2" >Wolverine Glacier - Air Temp2</option>
            <option value="WOL$Temp$AIR3" >Wolverine Glacier - Air Temp3</option>
            <option value="WOL$Dir$WIND1">Wolverine Glacier - Wind Direction1</option>
            <option value="WOL$Dir$WIND2">Wolverine Glacier - Wind Direction1</option>
            <option value="WOL$Speed$Wind">Wolverine Glacier - Wind Speed1</option>
            <option value="WOL$Speed$WIND2">Wolverine Glacier - Wind Speed2</option>
            <option value="WOL$Precip$Inst">Wolverine Glacier - Precipitation</option>
          </optgroup>
  
          <optgroup label="Cumulative Graphs/Analysis">
            <option value="WOL$ND$WindDirVsSpeed">Wind Direction vs. Speed</option>
            <option value="WOL$ND$WindSpeedSensorCompare">Wind Speed Comparison</option>     
          </optgroup>
  
        </select>

-----Original Message-----
