### ISSUE TITLE
Enable Valdez Glacier real-time data

### ISSUE THREAD

**Issue by adamlewinter** [gadomski/glac.io#133]
I'm working on the Overview, Images, and Climate Station Diagram content for the remaining USGS climate stations. @gadomski, will you work with @dcfinnegan to enable the real-time data feed?

**Comment by gadomski** [comment]
@adamlewinter Valdez data is up on the dev site at http://gadomski.github.io/glac.io/locations/valdez/data.html. Can you poke and make sure it all looks ok? If so, I'll push as is, and we can fill in the overview and stuff later.

Should we include Valdez (and these other sites) in the Location drop down at the top of the page, or should we keep that list short with just the main locations?

**Comment by adamlewinter** [comment]
@gadomski Valdez data looks good to go.
