### ISSUE TITLE
Enable Gulkana Glacier real-time data

### ISSUE THREAD

**Issue by adamlewinter** [gadomski/glac.io#134]
I'm working on the Overview, Images, and Climate Station Diagram content for the remaining USGS climate stations. @gadomski, will you work with @dcfinnegan to enable the real-time data feed?

**Comment by gadomski** [comment]
@dcfinnegan do you have ts code information for this station? Thanks.

**Comment by dcfinnegan** [comment]
8810021	T	T	NAE	GUL.Dir-WIND2.Inst.15Minutes.0.DCP-raw	deg	Angle	GUL
14624021	T	T	NAE	GUL.Rad-SOLARDOWN4.Inst.15Minutes.0.DCP-raw	J/m2	Irradiation	GUL
14623021	T	T	NAE	GUL.Rad-SOLARUP4.Inst.15Minutes.0.DCP-raw	J/m2	Irradiation	GUL
14622021	T	T	NAE	GUL.Volt-4.Inst.15Minutes.0.DCP-raw	volt	Electromotive Potential	GUL
14620021	T	T	NAE	GUL.Depth-SNOW4.Inst.15Minutes.0.DCP-raw	mm	Length	GUL
14618021	T	T	NAE	GUL.Dir-WIND4.Inst.15Minutes.0.DCP-raw	deg	Angle	GUL
14616021	T	T	NAE	GUL.Speed-WIND4.Inst.15Minutes.0.DCP-raw	kph	Linear Speed	GUL
14610021	T	T	NAE	GUL.Temp-AIR4.Inst.15Minutes.0.DCP-raw	C	Temperature	GUL
8813021	T	T	NAE	GUL.Speed-WIND2.Inst.15Minutes.0.DCP-raw	kph	Linear Speed	GUL
8811021	T	T	NAE	GUL.Volt.Inst.1Hour.0.DCP-raw	volt	Electromotive Potential	GUL
25947021	T	T	NAE	GUL.Precip-4.Inst.15Minutes.0.DCP-raw	mm	Length	GUL
8809021	T	T	NAE	GUL.Dir-WIND1.Inst.15Minutes.0.DCP-raw	deg	Angle	GUL
8804021	T	T	NAE	GUL.Temp-AIR1.Inst.15Minutes.0.DCP-raw	C	Temperature	GUL
8805021	T	T	NAE	GUL.Temp-AIR2.Inst.15Minutes.0.DCP-raw	C	Temperature	GUL
8806021	T	T	NAE	GUL.Temp-AIR3.Inst.15Minutes.0.DCP-raw	C	Temperature	GUL
8807021	T	T	NAE	GUL.Precip.Inst.15Minutes.0.DCP-raw	mm	Length	GUL
8808021	T	T	NAE	GUL.Speed-Wind.Inst.15Minutes.0.DCP-raw	kph	Linear Speed	GUL

**Comment by gadomski** [comment]
Deployed to the dev side, @adamlewinter can you check? Thanks.

**Comment by adamlewinter** [comment]
@gadomski For the Gulkana data, my observations, but the issues are likely in the data, not it the data display:

These are good: 
-Voltage
-Solar Radiation Up
-Solar Radiation Down
-Wind Speed
-Wind Direction 1 and 3
-Snow Depth
-Precipitation

Problems:
-Wind Direction 2: Looks like it got messed up around April 2012
-Air temp ends July 24, 2014

**Comment by gadomski** [comment]
I agree with both of those problem. Want me to make a different sensor (maybe snow depth) the default so we start with a sensor that has a good time range?

Don't know what we could do about wind sensor 2, unless you just want me to disable it?

**Comment by adamlewinter** [comment]
Let's default to precipitation for now, and disable wind sensor 2. I'll ping Shad and see about this issue. Thanks!

**Comment by gadomski** [comment]
Awesome, thanks Adam. I'll push up the latest stuff to the live site, but will keep these tickets open for filling out context, etc.

**Comment by dcfinnegan** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

  
        <optgroup label="Gulkana Glacier">
          <option style="color:red;" value="GUL$Volt$">Gulkana Glacier - Battery Voltage </option> 
          <option value="GUL$Temp$AIR1" selected="selected">Gulkana Glacier - Air Temp1</option>
          <option value="GUL$Temp$AIR2" >Gulkana Glacier - Air Temp2</option>
          <option value="GUL$Temp$AIR3" >Gulkana Glacier - Air Temp3</option>
          <option value="GUL$Dir$WIND1">Gulkana Glacier - Wind Direction1</option>
          <option value="GUL$Dir$WIND2">Gulkana Glacier - Wind Direction2</option>
          <option value="GUL$Speed$Wind">Gulkana Glacier - Wind Speed1</option>
          <option value="GUL$Speed$WIND2">Gulkana Glacier - Wind Speed2</option>
          <option value="GUL$Precip$Inst">Gulkana Glacier - Precipitation</option>
        </optgroup>
        <optgroup label="Gulkana Glacier Iridium">
          <option style="color:red;" value="GUL$Volt$4">Gulkana Iridium - Battery Voltage </option> 
          <option value="GUL$Temp$AIR4">Gulkana Iridium - Air Temp</option>
          <option value="GUL$Dir$WIND4">Gulkana Iridium - Wind Direction</option>
          <option value="GUL$Speed$WIND4">Gulkana Iridium - Wind Speed</option>
          <option value="GUL$Rad$SOLARUP4">Gulkana Iridium - Solar Radiation Up</option>
          <option value="GUL$Rad$SOLARDOWN4">Gulkana Iridium - Solar Radiation Down</option>
          <option value="GUL$Depth$SNOW4">Gulkana Iridium - Snow Depth</option>
        </optgroup>
        <optgroup label="Cumulative Graphs/Analysis">
          <option value="GUL$ND$WindDirVsSpeed">Wind Direction vs. Speed</option>
          <option value="GUL$ND$WindSpeedSensorCompare">Wind Speed Comparison</option>
        </optgroup>

-----Original Message-----
